// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywqiWZpHhJHGZ23fmEO0M3dS3iJSAXmk',
    appId: '1:671038391479:web:8126c99b188175be5cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    authDomain: 'flutter-ddd-firebase-cou-cfc37.firebaseapp.com',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3vVRN5Nx6eTQHcDJfmsfU6t0u9zzceoA',
    appId: '1:671038391479:android:e76ac9180bc1d3fd5cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDotQ8QwW4lf2ByBpoiX3QrM_YM1_ehZBs',
    appId: '1:671038391479:ios:d037d66b2bce1fe95cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
    iosClientId: '671038391479-6qhholnpoftok8901mrgicmcfs7r3k9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDddFirebaseCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDotQ8QwW4lf2ByBpoiX3QrM_YM1_ehZBs',
    appId: '1:671038391479:ios:d037d66b2bce1fe95cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
    iosClientId: '671038391479-6qhholnpoftok8901mrgicmcfs7r3k9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDddFirebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAywqiWZpHhJHGZ23fmEO0M3dS3iJSAXmk',
    appId: '1:671038391479:web:743e2bdf0a18b5b15cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    authDomain: 'flutter-ddd-firebase-cou-cfc37.firebaseapp.com',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAywqiWZpHhJHGZ23fmEO0M3dS3iJSAXmk',
    appId: '1:671038391479:web:bb5fb36a912773dd5cf932',
    messagingSenderId: '671038391479',
    projectId: 'flutter-ddd-firebase-cou-cfc37',
    authDomain: 'flutter-ddd-firebase-cou-cfc37.firebaseapp.com',
    storageBucket: 'flutter-ddd-firebase-cou-cfc37.appspot.com',
  );
}
